# Config
baseurl: ""
url: "https://saveourhospo.github.io/"

# Site Settings
settings:
  title: "SaveOurHospo"
  description: "Help save your favourite restaurants, cafés and other venues by buying a voucher."
  email: "saveourhospo@gmail.com"
  img_placeholder: "https://source.unsplash.com/collection/2455617"
  rss: false

# Navigation Links
navigation:
  - {name: 'FAQ', link: '/faq'}

# Social Media Links
social:
  instagram: "https://www.instagram.com/cvgellhorn/"
  twitter: "https://twitter.com/cvgellhorn"
  github: "https://github.com/saveourhospo/saveourhospo.github.io"

# Translations
translations:
  fork_github: "Fork this project on GitHub"
  follow_instagram: "Follow us on Instagram"
  follow_twitter: "Follow us on Twitter"
  subscribe_rss: "Subscribe to our RSS"
  prev_page: "Prev Page"
  next_page: "Next Page"
  search_placeholder: "Search Venues..."
  no_result: "We couldn’t find any venues matching"
  donate: "Get a Voucher"
  mail_add_business: "Add Venue"
  mail_subject: "New%20Venue%20%5Bnew_venue%5D"
  mail_body: "%3Cb%3EPlease%20fill%20out%20the%20following%3C%2Fb%3E%0D%0A%0D%0AVenue%20Name%3A%0D%0AAddress%3A%0D%0ADonation%20Link%20or%20Contact%20Email%3A%0D%0ACover%20Image%20URL%20(optional)%3A"

# Pagination
paginate: 12
paginate_path: "locations/:num"

# Plugins
plugins:
  - jekyll-paginate

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE