# Config
baseurl: ""
url: "https://saveourhospo.github.io/"

# Page Settings
settings:
  title: "SaveOurHospo"
  description: "Save your favourite Sydney Restaurants, Cafes and Places by buying gift cards"
  email: "saveourhospo@gmail.com"
  img_placeholder: "https://source.unsplash.com/collection/2455617"
  rss: false

# Navigation Links
navigation:
  - {name: 'About', link: '/about'}

# Social Media Links
social:
  instagram: "https://www.instagram.com/cvgellhorn/"
  twitter: "https://twitter.com/cvgellhorn"
  github: "https://github.com/saveourhospo/saveourhospo.github.io"

# Translations
translations:
  fork_github: "Fork this project on GitHub"
  follow_instagram: "Follow us on Instagram"
  follow_twitter: "Follow us on Twitter"
  subscribe_rss: "Subscribe to our RSS"
  prev_page: "Prev Page"
  next_page: "Next Page"
  no_result: "We couldn’t find any locations matching"
  info: "Help save your favourite restaurants, cafes and other places by buying gift cards."
  donate: "Donate"

# Pagination
paginate: 12
paginate_path: "locations/:num"

# Plugins
plugins:
  - jekyll-paginate

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE