# Serving
baseurl: ""
url: "https://saveourhospo.org/"
host: 0.0.0.0

# Site Settings
settings:
  title: "SaveOurHospo"
  description: "Help save your favourite restaurants, cafés and other venues by buying a voucher or order home delivery."
  google_form: "https://docs.google.com/forms/d/e/1FAIpQLSdQIZd2b8caigbrxoZ41ohJqJm5t1ehQ8fNKnZANUC8Z9V7BQ/viewform"
  img_placeholder: "https://source.unsplash.com/collection/2455617"
  google_tracking_id: "UA-162570025-1"
  rss: false

# Front Matter Defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Navigation Links
navigation:
  - {name: 'About', link: '/about'}

# Social Media Links
social:
  github: "https://github.com/saveourhospo/saveourhospo.github.io"
  instagram: "https://www.instagram.com/saveourhospo/"

# Translations
translations:
  social:
    github: "Fork this project on GitHub"
    instagram: "Follow us on Instagram"
    twitter: "Follow us on Twitter"
  subscribe_rss: "Subscribe to our RSS"
  search_placeholder: "Search Venues..."
  no_result: "We couldn’t find any matching venues. If you want to add a new venue <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSdQIZd2b8caigbrxoZ41ohJqJm5t1ehQ8fNKnZANUC8Z9V7BQ/viewform\" target=\"_blank\">click here</a>"
  voucher_link: "Help Out"
  delivery_link: "Online Delivery"
  mail_add_business: "Add Venue"

# Pagination
paginate: 12
paginate_path: "page/:num"

# Plugins
plugins:
  - jekyll-paginate

# Excludes
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "tasks", "package.json", "package-lock.json", "README.md", "LICENSE", "saveourhospo-credentials.json"]
