# Config
baseurl: ""
url: "https://saveourhospo.org/"
host: 0.0.0.0

# Site Settings
settings:
  title: "SaveOurHospo"
  description: "Help save your favourite restaurants, cafés and other venues by buying a voucher or order home delivery."
  email: "saveourhospo@gmail.com"
  img_placeholder: "https://source.unsplash.com/collection/2455617"
  rss: false

# Front Matter Defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Navigation Links
navigation:
  - {name: 'FAQ', link: '/faq'}

# Social Media Links
social:
  github: "https://github.com/saveourhospo/saveourhospo.github.io"

# Translations
translations:
  social:
    github: "Fork this project on GitHub"
    instagram: "Follow us on Instagram"
    twitter: "Follow us on Twitter"
  subscribe_rss: "Subscribe to our RSS"
  prev_page: "Prev Page"
  next_page: "Next Page"
  search_placeholder: "Search Venues..."
  no_result: "We couldn’t find any matching venues"
  voucher_link: "Help Out"
  delivery_link: "Online Delivery"
  mail_add_business: "Add Venue"
  mail_subject: "SOH%20-%20New%20Venue"
  mail_body: "%3Cb%3EPlease%20fill%20out%20the%20following%3C%2Fb%3E%0D%0A%0D%0AVenue%20Name%3A%20%0D%0AVenue%20Address%3A%20%0D%0AVoucher%20or%20Donation%20Link%3A%20%0D%0AOnline%20Delivery%20Link%20(optional)%3A%0D%0ACover%20Image%20URL%20(optional)%3A%0D%0A%0D%0ADon't%20use%20copyright%20protected%20images%20without%20permission."

# Pagination
paginate: 12
paginate_path: "locations/:num"

# Plugins
plugins:
  - jekyll-paginate

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE